version: 2.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest

commands:
  npm-install:
    steps:
      - run:
          name: npm install
          command: npm install
  run-linter:
    steps:
      - run:
          name: npm run lint
          command: npm run lint
  test-command:
    steps:
      - run:
          name: hello world
          command: echo "hello world"

jobs:
  test-job:
    executor:
      name: default
    steps:
      - checkout
      - npm-install
      - run-linter
      - test-command

workflows:
  build:
    jobs:
      - test-job